# Database
db.host=localhost
db.port=5432
db.name=openplace
db.user=postgres
db.password=password
spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/${db.name}
spring.datasource.username=${db.user}
spring.datasource.password=${db.password}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog-root.xml

# API Key
api.key=<empty>
