-- liquibase formatted sql

-- changeset Robin.Mayer:1768770071-1
CREATE TABLE addresses
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street          VARCHAR(255) NOT NULL,
    house_number    VARCHAR(255) NOT NULL,
    post_code       VARCHAR(255) NOT NULL,
    city            VARCHAR(255) NOT NULL,
    latitude        DOUBLE PRECISION NOT NULL,
    longitude       DOUBLE PRECISION NOT NULL
);
